/**
 * Rakijazios M2a: OS-aware runner installers served by the api.
 *
 * - install.sh  (Linux/macOS): `curl -fsSL <origin>/api/local-runners/install.sh | sh -s -- --code XXXX-XXXX`
 * - install.ps1 (Windows):     run by a downloaded `.cmd` (code baked in) or a PowerShell one-liner
 *
 * The runner files come from a read-only bundle directory, are hashed once at startup
 * and served from memory, so the bytes served are exactly the bytes hashed into the
 * scripts. Node.js is used when >= 22.18 is installed; otherwise a portable, pinned
 * Node.js is downloaded from nodejs.org and checked against a pinned SHA-256.
 * Nothing here contains a secret: the one-time pairing code is passed as an argument
 * (Linux/macOS) or an environment variable (Windows), never in a URL.
 */
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export const NODE_VERSION = "22.23.2";
/** From https://nodejs.org/dist/v22.23.2/SHASUMS256.txt (verified 2026-10-08). */
export const NODE_SHA256: Record<string, string> = {
  "linux-x64": "b294a556e639d64338823920e5866c21c02741742d2e1529ee1a225c1ec9252a",
  "linux-arm64": "013b59cfd2819703a6f4a14ab891fc46fc2a4e3f5bcd92de3fb4929b43e35b30",
  "darwin-x64": "58e99022c2ff89395576cc7fd4d98cea24bb68081475d5f88b801ee8729fb026",
  "darwin-arm64": "61130f394c1630d211dd50aecc4353d379480f36d3ac913cd85dbba1aed585c6",
  "win-x64": "1177b4137ba5adaa56354ae40f1080c7450e8ae09cecb47da459d1c52ac99f97",
  "win-arm64": "fec025a6da31757e3b6af84c5a1628e9d38442ca99a2161091d78f2fcfa35ef3",
};

/** Served runner files: name in the URL → path inside the installed app dir. */
export const RUNNER_FILES: ReadonlyArray<{ name: string; path: string }> = [
  { name: "package.json", path: "package.json" },
  { name: "index.ts", path: "src/index.ts" },
  { name: "client.ts", path: "src/client.ts" },
  { name: "config.ts", path: "src/config.ts" },
  { name: "discover.ts", path: "src/discover.ts" },
  { name: "loopback.ts", path: "src/loopback.ts" },
  { name: "pair.ts", path: "src/pair.ts" },
  { name: "protocol.ts", path: "src/protocol.ts" },
];

export type RunnerBundle = {
  version: string;
  files: Array<{ name: string; path: string; sha256: string; body: Buffer }>;
};

export function loadRunnerBundle(dir: string): RunnerBundle | null {
  if (!existsSync(dir)) return null;
  try {
    const files = RUNNER_FILES.map((f) => {
      const body = readFileSync(join(dir, f.path));
      return { ...f, body, sha256: createHash("sha256").update(body).digest("hex") };
    });
    const index = files.find((f) => f.name === "index.ts")!.body.toString("utf8");
    const version = /export const VERSION = "([^"]+)"/.exec(index)?.[1] ?? "unknown";
    return { version, files };
  } catch {
    return null;
  }
}

/** Origins are validated URLs; keep them out of any shell/PowerShell quoting trouble. */
export function safeOrigin(origin: string): string {
  const url = new URL(origin);
  if (url.protocol !== "http:" && url.protocol !== "https:") throw new Error("bad origin");
  const o = url.origin;
  if (/['"`$\\\s;&|<>]/.test(o)) throw new Error("bad origin");
  return o;
}

export function renderInstallSh(originRaw: string, bundle: RunnerBundle): string {
  const origin = safeOrigin(originRaw);
  const fetches = bundle.files
    .map((f) => `fetch_file '${f.name}' '${f.path}' '${f.sha256}'`)
    .join("\n");
  return `#!/bin/sh
# Rakijazios local runner installer (Linux / macOS), generated by ${origin}
# Runner ${bundle.version}. Usage:
#   curl -fsSL '${origin}/api/local-runners/install.sh' | sh -s -- --code XXXX-XXXX [--no-autostart] [--name "My PC"]
# What it does: installs the runner for this user only (no sudo), verifies every file's
# SHA-256, pairs this computer with the one-time code, starts the runner and (optionally)
# starts it at login. The runner only connects OUT to ${origin}; it opens no port and only
# talks to a model server on this computer (127.0.0.1).
set -eu
SERVER='${origin}'
VERSION='${bundle.version}'
NODE_VERSION='${NODE_VERSION}'
CODE=''
NAME=''
AUTOSTART=1
while [ $# -gt 0 ]; do
  case "$1" in
    --code) [ $# -ge 2 ] || { echo "--code needs a value" >&2; exit 2; }; CODE="$2"; shift 2 ;;
    --name) [ $# -ge 2 ] || { echo "--name needs a value" >&2; exit 2; }; NAME="$2"; shift 2 ;;
    --no-autostart) AUTOSTART=0; shift ;;
    --autostart) AUTOSTART=1; shift ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
done
say() { printf '%s\\n' "$*"; }
die() { printf 'Error: %s\\n' "$*" >&2; exit 1; }
[ -n "$CODE" ] || die "missing --code. Get one in Rakijazios: Settings > My hardware > Add a computer."
command -v curl >/dev/null 2>&1 || die "curl is required"
command -v tar >/dev/null 2>&1 || die "tar is required"
umask 077
case "$(uname -s)" in Linux) PLAT=linux ;; Darwin) PLAT=darwin ;; *) die "unsupported system $(uname -s) (on Windows use the Windows installer)" ;; esac
case "$(uname -m)" in x86_64|amd64) ARCH=x64 ;; aarch64|arm64) ARCH=arm64 ;; *) die "unsupported CPU $(uname -m)" ;; esac
PREFIX="\${RAKAZO_RUNNER_HOME:-$HOME/.local/share/rakijazios-runner}"
BIN_DIR="\${RAKAZO_RUNNER_BIN_DIR:-$HOME/.local/bin}"
sha256() { if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1; else shasum -a 256 "$1" | cut -d' ' -f1; fi; }
verify() { [ "$(sha256 "$1")" = "$2" ] || die "checksum mismatch for $(basename "$1"); nothing was installed"; }
mkdir -p "$PREFIX" "$BIN_DIR"
TMP="$(mktemp -d "\${TMPDIR:-/tmp}/rakijazios.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT INT TERM
say "Rakijazios runner $VERSION -> $PREFIX"

# 1. Node.js >= 22.18: use the installed one, or a private portable copy for the runner only.
NODE=''
if command -v node >/dev/null 2>&1 && node -e 'const [a,b]=process.versions.node.split(".").map(Number);process.exit(a>22||(a===22&&b>=18)?0:1)' >/dev/null 2>&1; then
  NODE="$(command -v node)"
fi
if [ -z "$NODE" ]; then
  NODE_DIR="$PREFIX/node-v$NODE_VERSION-$PLAT-$ARCH"
  if [ ! -x "$NODE_DIR/bin/node" ]; then
    case "$PLAT-$ARCH" in
${Object.entries(NODE_SHA256)
  .filter(([k]) => !k.startsWith("win"))
  .map(([k, v]) => `      ${k}) SUM='${v}' ;;`)
  .join("\n")}
      *) die "no portable Node.js for $PLAT-$ARCH" ;;
    esac
    say "Downloading Node.js $NODE_VERSION (portable, used only by the runner)..."
    curl -fsSL "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-$PLAT-$ARCH.tar.gz" -o "$TMP/node.tgz"
    verify "$TMP/node.tgz" "$SUM"
    tar -xzf "$TMP/node.tgz" -C "$PREFIX"
  fi
  NODE="$NODE_DIR/bin/node"
fi
say "Node.js: $("$NODE" --version) ($NODE)"

# 2. Runner files, each checked against the SHA-256 published by this server.
fetch_file() {
  mkdir -p "$(dirname "$TMP/app/$2")"
  curl -fsSL "$SERVER/api/local-runners/runner/files/$1" -o "$TMP/app/$2"
  verify "$TMP/app/$2" "$3"
}
${fetches}
rm -rf "$PREFIX/app.old"
[ -d "$PREFIX/app" ] && mv "$PREFIX/app" "$PREFIX/app.old"
mv "$TMP/app" "$PREFIX/app"
rm -rf "$PREFIX/app.old"

# 3. Launcher: $BIN_DIR/rakazo-runner
LAUNCHER="$PREFIX/rakazo-runner"
{
  echo '#!/bin/sh'
  if [ -n "\${RAKAZO_RUNNER_CONFIG_DIR:-}" ]; then echo "export RAKAZO_RUNNER_CONFIG_DIR='$RAKAZO_RUNNER_CONFIG_DIR'"; fi
  if [ -n "\${RAKAZO_RUNNER_SERVICE:-}" ]; then echo "export RAKAZO_RUNNER_SERVICE='$RAKAZO_RUNNER_SERVICE'"; fi
  echo "exec '$NODE' '$PREFIX/app/src/index.ts' \\"\\$@\\""
} > "$LAUNCHER"
chmod 700 "$LAUNCHER"
ln -sf "$LAUNCHER" "$BIN_DIR/rakazo-runner"

# 4. Pair with the one-time code (the device key is written to a private file, never shown).
if [ -n "$NAME" ]; then "$LAUNCHER" pair --server "$SERVER" --code "$CODE" --name "$NAME"; else "$LAUNCHER" pair --server "$SERVER" --code "$CODE"; fi
"$LAUNCHER" stop >/dev/null 2>&1 || true

# 5. Start now, and at login if wanted.
if [ "$AUTOSTART" = 1 ] && [ "$PLAT" = linux ] && command -v systemctl >/dev/null 2>&1 && systemctl --user show-environment >/dev/null 2>&1; then
  SVC="\${RAKAZO_RUNNER_SERVICE:-rakijazios-runner}"
  UNIT_DIR="\${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
  mkdir -p "$UNIT_DIR"
  cat > "$UNIT_DIR/$SVC.service" <<UNIT
[Unit]
Description=Rakijazios local runner (outbound only; shares your local AI model)
After=network-online.target

[Service]
ExecStart="$LAUNCHER" run
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
UNIT
  systemctl --user daemon-reload
  systemctl --user enable "$SVC.service" >/dev/null 2>&1
  systemctl --user restart "$SVC.service"
  say "Starts automatically when you log in (systemd user service $SVC)."
  say "Tip: to keep it running after you log out: loginctl enable-linger $(id -un)"
elif [ "$AUTOSTART" = 1 ] && [ "$PLAT" = darwin ]; then
  LABEL="\${RAKAZO_RUNNER_SERVICE:-com.rakijazios.runner}"
  PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
  mkdir -p "$HOME/Library/LaunchAgents"
  cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key><array><string>$LAUNCHER</string><string>run</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><dict><key>SuccessfulExit</key><false/></dict>
  <key>StandardErrorPath</key><string>$HOME/.config/rakazo-runner/runner.log</string>
</dict></plist>
PLIST
  launchctl bootout "gui/$(id -u)/$LABEL" >/dev/null 2>&1 || true
  launchctl bootstrap "gui/$(id -u)" "$PLIST"
  say "Starts automatically when you log in (launchd agent $LABEL)."
else
  "$LAUNCHER" start
fi
sleep 3
"$LAUNCHER" status || true
case ":$PATH:" in *":$BIN_DIR:"*) ;; *) say "(Add $BIN_DIR to your PATH to use the rakazo-runner command.)" ;; esac
say "Done. Go back to Rakijazios: the dialog shows 'connected' within a few seconds."
`;
}

export function renderInstallPs1(originRaw: string, bundle: RunnerBundle): string {
  const origin = safeOrigin(originRaw);
  const files = bundle.files
    .map((f) => `    @('${f.name}', '${f.path.replace(/\//g, "\\")}', '${f.sha256}')`)
    .join(",\n");
  const ps = `# Rakijazios local runner installer (Windows), generated by ${origin}
# Runner ${bundle.version}. Run by the downloaded "Rakijazios-connect.cmd", or in PowerShell:
#   $env:RAKAZO_PAIR_CODE='XXXX-XXXX'; irm '${origin}/api/local-runners/install.ps1' | iex
# Installs for this user only (no admin), verifies every file's SHA-256, pairs this computer
# with the one-time code and starts the runner. The runner only connects OUT to ${origin};
# it opens no port and only talks to a model server on this computer (127.0.0.1).
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
$Server = '${origin}'
$Version = '${bundle.version}'
$NodeVersion = '${NODE_VERSION}'
$Code = $env:RAKAZO_PAIR_CODE
if (-not $Code) { throw 'Missing pairing code. Get one in Rakijazios: Settings > My hardware > Add a computer.' }
$Autostart = $env:RAKAZO_NO_AUTOSTART -ne '1'
$Prefix = if ($env:RAKAZO_RUNNER_HOME) { $env:RAKAZO_RUNNER_HOME } else { Join-Path $env:LOCALAPPDATA 'Rakijazios\\runner' }
New-Item -ItemType Directory -Force -Path $Prefix | Out-Null
$Tmp = Join-Path ([IO.Path]::GetTempPath()) ('rakijazios-' + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $Tmp | Out-Null
function Assert-Hash([string]$Path, [string]$Expected) {
  $got = (Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLowerInvariant()
  if ($got -ne $Expected) { throw ('Checksum mismatch for ' + (Split-Path -Leaf $Path) + '; nothing was installed.') }
}
function Get-RemoteFile([string]$Url, [string]$Out) { Invoke-WebRequest -UseBasicParsing -Uri $Url -OutFile $Out }
try {
  Write-Host "Rakijazios runner $Version -> $Prefix"
  # 1. Node.js >= 22.18: the installed one, or a private portable copy for the runner only.
  $Node = $null
  $sys = Get-Command node -ErrorAction SilentlyContinue
  if ($sys) {
    try { $v = & $sys.Source -p 'process.versions.node'; if ([version]$v -ge [version]'22.18.0') { $Node = $sys.Source } } catch { }
  }
  if (-not $Node) {
    $arch = if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64') { 'arm64' } else { 'x64' }
    $sums = @{ 'x64' = '${NODE_SHA256["win-x64"]}'; 'arm64' = '${NODE_SHA256["win-arm64"]}' }
    $name = "node-v$NodeVersion-win-$arch"
    $Node = Join-Path $Prefix "$name\\node.exe"
    if (-not (Test-Path -LiteralPath $Node)) {
      Write-Host "Downloading Node.js $NodeVersion (portable, used only by the runner)..."
      $zip = Join-Path $Tmp 'node.zip'
      Get-RemoteFile "https://nodejs.org/dist/v$NodeVersion/$name.zip" $zip
      Assert-Hash $zip $sums[$arch]
      Expand-Archive -LiteralPath $zip -DestinationPath $Prefix -Force
    }
  }
  Write-Host ('Node.js: ' + (& $Node --version) + " ($Node)")
  # 2. Runner files, each checked against the SHA-256 published by this server.
  $App = Join-Path $Tmp 'app'
  New-Item -ItemType Directory -Force -Path (Join-Path $App 'src') | Out-Null
  $files = @(
${files}
  )
  foreach ($f in $files) {
    $out = Join-Path $App $f[1]
    Get-RemoteFile "$Server/api/local-runners/runner/files/$($f[0])" $out
    Assert-Hash $out $f[2]
  }
  $Dest = Join-Path $Prefix 'app'
  if (Test-Path -LiteralPath $Dest) { Remove-Item -Recurse -Force -LiteralPath $Dest }
  Move-Item -LiteralPath $App -Destination $Dest
  $Index = Join-Path $Dest 'src\\index.ts'
  Set-Content -LiteralPath (Join-Path $Prefix 'rakazo-runner.cmd') -Encoding ASCII -Value ('@echo off' + [Environment]::NewLine + '"' + $Node + '" "' + $Index + '" %*')
  # 3. Pair with the one-time code (the device key goes to a private file, never shown).
  & $Node $Index pair --server $Server --code $Code
  if ($LASTEXITCODE -ne 0) { throw 'Pairing failed (see the message above).' }
  & $Node $Index stop | Out-Null
  # 4. Start now, and at sign-in if wanted (Startup folder, hidden window).
  if ($Autostart) {
    $vbs = Join-Path ([Environment]::GetFolderPath('Startup')) 'Rakijazios runner.vbs'
    Set-Content -LiteralPath $vbs -Encoding ASCII -Value ('CreateObject("WScript.Shell").Run """' + $Node + '"" ""' + $Index + '"" start", 0, False')
    Write-Host 'Starts automatically when you sign in to Windows.'
  }
  & $Node $Index start
  Start-Sleep -Seconds 3
  & $Node $Index status
  Write-Host "Done. Go back to Rakijazios: the dialog shows 'connected' within a few seconds."
} finally {
  Remove-Item -Recurse -Force -LiteralPath $Tmp -ErrorAction SilentlyContinue
}
`;
  return ps.replace(/\r?\n/g, "\r\n");
}

/** Double-click installer for Windows, with the one-time code baked in. */
export function renderWindowsCmd(originRaw: string, code: string, autostart: boolean): string {
  const origin = safeOrigin(originRaw);
  if (!/^[0-9A-Z]{4}-[0-9A-Z]{4}$/.test(code)) throw new Error("bad code");
  return [
    "@echo off",
    "setlocal",
    "title Rakijazios - connect this computer",
    "echo Connecting this computer to Rakijazios (one-time code, valid for 10 minutes)...",
    "echo The runner only connects out to " + origin + " and opens no port.",
    "echo.",
    `set "RAKAZO_PAIR_CODE=${code}"`,
    ...(autostart ? [] : ['set "RAKAZO_NO_AUTOSTART=1"']),
    `powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((Invoke-WebRequest -UseBasicParsing -Uri '${origin}/api/local-runners/install.ps1').Content)"`,
    "echo.",
    "pause",
    "",
  ].join("\r\n");
}

export function installCommands(originRaw: string, code: string) {
  const origin = safeOrigin(originRaw);
  const sh = `curl -fsSL '${origin}/api/local-runners/install.sh' | sh -s -- --code ${code}`;
  return {
    unix: sh,
    unixNoAutostart: `${sh} --no-autostart`,
    powershell: `$env:RAKAZO_PAIR_CODE='${code}'; irm '${origin}/api/local-runners/install.ps1' | iex`,
    powershellNoAutostart: `$env:RAKAZO_PAIR_CODE='${code}'; $env:RAKAZO_NO_AUTOSTART='1'; irm '${origin}/api/local-runners/install.ps1' | iex`,
    windowsCmd: renderWindowsCmd(origin, code, true),
    windowsCmdNoAutostart: renderWindowsCmd(origin, code, false),
  };
}
